pbslacks V0.9 Date : 22 janvier 2020 Auteur : Pierre Brochard (pierre.brochard.1982@m4x.org) Copyright et droits d'auteurs : Pierre Brochard Some reworking.

diff --git a/pbsetup b/pbsetup
--- a/pbsetup
+++ b/pbsetup
@@ -7,7 +7,7 @@
 . "$(dirname $0)/pbinclude"
 
 xhelp () {
-    mygt 'Launch this script in a directory containing slackware64-current\nor slackware64 or from the current directory for a new clone.'|sed 's@\\n@\n@'
+    mygt 'Launch this script in a directory containing slackware64-current\nor slackware64 or from the current directory for a new clone.'|sed 's@\\n@\n@g'
     echo
     echo "> [../]pbslack/pbsetup [-test] [-h|-help] [-nodial]"
 }
@@ -32,9 +32,15 @@ fi
 
 PBSLACKSPWD="$(dirname $0)"
 SLREPO=$(basename "$MYPWD"|cut -c1-14)
-
 XTEMPOUT=$(mktemp -p /tmp -t pbsetupout.XXXXXX)
 XTEMPMES=$(mktemp -p /tmp -t pbsetupmes.XXXXXX)
+
+cleanup () {
+    rm -f $XTEMPOUT
+    rm -f $XTEMPMES
+}
+
+trap 'echo "*** Ctrl-C caught -- aborting operations ***"; cleanup; exit 1' 2 14 15 # trap Ctrl-C and kill
 
 if [ $XTEST -ne 1 -a "$0" = "$PBMYPROG" -a "$SLREPO" != 'Slackware-x64-' ] ;then
     test_slack () {
@@ -57,7 +63,7 @@ if [ $XTEST -ne 1 -a "$0" = "$PBMYPROG" -a "$SLREPO" != 'Slackware-x64-' ] ;then
 	    echo '------------------------------------'
 	    echo "  $pactit"
 	    echo '------------------------------------'
-	    echo "$pactext"|sed 's@\\n@\n@'
+	    echo "$pactext"|sed 's@\\n@\n@g'
 	    read c
 	fi
 	if [ "$c" = 'y' ] ;then
@@ -80,43 +86,52 @@ HOMESLACK="$MYPWD"
 XUPASPIRE=on
 XUPUPGRADE=off
 XUPMAKEUSB=off
+XUPREFIND=off
 ASPIRE=$(mygt 'Get/Update local repository versus officiel remote Slackware and add-on packages')
 UPGRADE=$(mygt 'Sync/Update system to the last fetched current Slackware and add-on packages')
 MAKEUSB=$(mygt 'Make a bootable USB stick for Slackware install.')
+REFIND=$(mygt 'Install the refind boot manager for dual or more boot.')
 
 xmaster () {
     defitem=$1;shift
-    xsel1=$1;shift;xsel2=$1;shift;xsel3=$1
-    pactit=$(mygt 'Main menu')
+    xsel1=$1;shift;xsel2=$1;shift;xsel3=$1;shift;xsel4=$1
+    pactit=$(mygt 'Main menu');pactit="pbsetup: $pactit"
     pactext=$(mygt 'Choose your actions below')
     if [ $ISDIAL -eq 1 ] ;then
-	dialog --colors --title "$pactit" --default-item $defitem --defaultno \
-	    --separate-output --item-help --help-button --help-status \
-	    --checklist "$pactext" 0 100 3 \
+	dialog --colors --title "$pactit" --default-item $defitem \
+	    --defaultno --separate-output --item-help --help-button \
+	    --help-status --checklist "$pactext" 0 100 4 \
 	    aspire "$ASPIRE" $xsel1 aspire \
 	    upgrade "$UPGRADE" $xsel2 upgrade \
-	    makeusb "$MAKEUSB" $xsel3 makeusb
+	    makeusb "$MAKEUSB" $xsel3 makeusb \
+	    refind "$MAKEUSB" $xsel4 refind
     else
 	echo '------------------------------------'
 	echo "          $pactit"
 	echo '------------------------------------'
-	echo "HELP aspire (y or n) :";read c
-	if [ "$c" = "y" ] ;then echo "HELP aspire" 1>&2;return;fi
-	echo "HELP upgrade (y or n) :";read c
-	if [ "$c" = "y" ] ;then echo "HELP upgrade" 1>&2;return;fi
-	echo "HELP makeusb (y or n) :";read c
-	if [ "$c" = "y" ] ;then echo "HELP makeusb" 1>&2;return;fi
-
+	echo "HELP (y or n) :";read c
+	if [ "$c" = "y" ] ;then
+	    echo "HELP aspire (y or n) :";read c
+	    if [ "$c" = "y" ] ;then echo "HELP aspire" 1>&2;return;fi
+	    echo "HELP upgrade (y or n) :";read c
+	    if [ "$c" = "y" ] ;then echo "HELP upgrade" 1>&2;return;fi
+	    echo "HELP makeusb (y or n) :";read c
+	    if [ "$c" = "y" ] ;then echo "HELP makeusb" 1>&2;return;fi
+	    echo "HELP refind (y or n) :";read c
+	    if [ "$c" = "y" ] ;then echo "HELP refind" 1>&2;return;fi
+	fi
 	echo "$ASPIRE (y or n) :";read c
 	[ "$c" = "y" ] && echo "aspire" 1>&2
 	echo "$UPGRADE (y or n) :";read c
 	[ "$c" = "y" ] && echo "upgrade" 1>&2
 	echo "$MAKEUSB (y or n) :";read c
 	[ "$c" = "y" ] && echo "makeusb" 1>&2
+	echo "$REFIND (y or n) :";read c
+	[ "$c" = "y" ] && echo "refind" 1>&2
     fi
 }
 
-xsel="$XUPASPIRE $XUPUPGRADE $XUPMAKEUSB"
+xsel="$XUPASPIRE $XUPUPGRADE $XUPMAKEUSB $XUPREFIND"
 ditem=aspire
 bclaide=1
 
@@ -140,6 +155,8 @@ while [ $bclaide -eq 1 ] ;do
 	    pacaide=$(mygt 'Upgrade the local system with the local clone.')
 	elif [ "$xitem" = makeusb ] ;then
 	    pacaide=$(mygt 'Make a dual boot install USB stick with Slackware install and GParted Live which can boot on old bios or new UEFI bios computers.')
+	elif [ "$xitem" = refind ] ;then
+	    pacaide=$(mygt 'Setup the boot manager refind if you have set elilo in the installation of Slackware and you have other systems like MS Windows.')
 	fi
 	if [ $ISDIAL -eq 1 ] ;then
 	    dialog --colors --title "$xitem" --msgbox "$pacaide" 20 80
@@ -147,9 +164,7 @@ while [ $bclaide -eq 1 ] ;do
 	    echo '------------------------------------'
 	    echo "          $xitem"
 	    echo '------------------------------------'
-	    echo "$pacaide"|sed 's@\\n@\n@'
-	    mygt "Press a key to continue."
-	    read c
+	    echo "$pacaide"|sed 's@\\n@\n@g'
 	fi
     fi
 done
@@ -159,19 +174,24 @@ PBDIAL=;[ $ISDIAL -eq 0 ] && PBDIAL='-nodial'
 ISUSB=0
 ISASPIRE=0
 ISUPGRADE=0
+ISREFIND=0
 
 while read i;test "$i" != "" ;do
     [ "$(echo $i|cut -c1-4)" = 'HELP' ] && continue
     [ "$i" = aspire ] && ISASPIRE=1
     [ "$i" = upgrade ] && ISUPGRADE=1
     [ "$i" = makeusb ] && ISUSB=1
+    [ "$i" = refind ] && ISREFIND=1
 done < $XTEMPOUT
 
+# Aspire
 if [ $ISASPIRE -eq 1 ] ;then
     "$PBSLACKSPWD/pbaspire" $PBTEST $PBDIAL
     mygt "Clone done (full or partial depending on selected options)." \
 	>> $XTEMPMES
 fi
+
+# Upgrade
 if [ $ISUPGRADE -eq 1 ] ;then
     MYSCR='screen -S pbupgrade'
     if [ $XTEST -eq 1 -o $UID -eq 0 ]; then
@@ -182,6 +202,8 @@ if [ $ISUPGRADE -eq 1 ] ;then
     fi
     mygt "Upgrade done for selected set of packages." >> $XTEMPMES
 fi
+
+# Makeusb
 if [ $ISUSB -eq 1 ] ;then
     if [ $XTEST -eq 1 -o $UID -eq 0 ]; then
         "$PBSLACKSPWD/pbmakeusb" -ask $PBTEST
@@ -193,6 +215,24 @@ if [ $ISUSB -eq 1 ] ;then
 	mygt "USB stick created." >> $XTEMPMES
     else
 	mygt "USB stick not created." >> $XTEMPMES
+    fi
+fi
+
+# Install refind
+if [ $ISREFIND -eq 1 ] ;then
+    if [ $XTEST -eq 0 -a -d /boot/efi/EFI/Slackware ] ;then
+	xrefind=$(xlast /usr/share/refind-0)/install.sh
+	if [ $UID -eq 0 ]; then
+	    $xrefind
+	else
+	    mygt 'Change to root.'
+	    su - root -c "(cd \"$MYPWD\";$xrefind)"
+	fi
+    fi
+    if [ $? -eq 0 -a -d /boot/efi/EFI/Slackware ] ;then
+	mygt "refind installed." >> $XTEMPMES
+    else
+	mygt "refind not installed." >> $XTEMPMES
     fi
 fi
 
