pbslacks V0.9 Date : 22 janvier 2020 Auteur : Pierre Brochard (pierre.brochard.1982@m4x.org) Copyright et droits d'auteurs : Pierre Brochard Some reworking.

diff --git a/pbupgrade b/pbupgrade
--- a/pbupgrade
+++ b/pbupgrade
@@ -7,24 +7,13 @@
 . "$(dirname $0)/pbinclude"
 
 xhelp () {
-    cat <<EOF
-  Script a lancer dans le repertoire contenant slackware64 or slackware64-current
-deja aspire.
-  Ce repertoire peut etre la cle USB bootable d'installation.
-  pbslacks doit aussi etre accessible du repertoire courant.
-
-  Launch this script in the directory including alreadey cloned slackware64 or
-slackware64-current.
-  It can be on the bootable slackware install USB stick.
-  pbslacks should also be there.
-
-  > cd .../slackware-current"
-or> cd /run/media/$USER/USBSLACKINS/SlackDVD
-  > pbslacks/pbupgrade [-new (no system update)]
-               [-test (test only, no actions)]
-               [-help|-h] [-nodial]
-               [-post (actions to do preferably after a postinstall reboot)]
-EOF
+    mygt 'Launch this script in the directory including alreadey cloned slackware64 or slackware64-current.\nIt can be on the bootable slackware install USB stick.\npbslacks should also be there.'|sed 's@\\n@\n@g'
+    echo
+    echo '  > cd .../Slackware-x64-date'
+    echo 'or> cd /run/media/$USER/USBSLACKINS/SlackDVD'
+    echo '  > pbslacks/pbupgrade [-new (no system update)]'
+    echo '       [-test (test only, no actions)] [-help|-h] [-nodial]'
+    echo '       [-post (actions to do preferably after a postinstall reboot)]'
 }
 
 XNEW=
@@ -47,10 +36,11 @@ while [ $# -ge 1 ] ;do
     shift
 done
 
+XTEMPOUT=$(mktemp -p /tmp -t pbupgradeout.XXXXXX)
+XTEMPMES=$(mktemp -p /tmp -t pbupgrademes.XXXXXX)
+
 if [ ! -d /boot ] ;then
-    echo "Do the install of the Slackware Linux distribution before :"
-    echo "-see the doc/SLACKWARE.txt file."
-    exit 1
+    mygt "Do the install of the Slackware Linux distribution before :\n-see the doc/SLACKWARE.txt file." |sed 's@\\n@\n@g' > $XTEMPMES
 fi
 
 if [ $XTEST -ne 1 ] ;then
@@ -58,16 +48,18 @@ if [ $XTEST -ne 1 ] ;then
 	cd slackware64-current
     fi
     if [ ! -d slackware64 -o '(' ! -h pbslacks -a ! -d pbslacks ')' ] ;then
-	xhelp
-	exit 1
+	echo 'slackware64 or pbslacks not found.'> $XTEMPMES
+	xhelp >> $XTEMPMES
     fi
+fi
+
+if [ -s "$XTEMPMES" ] ;then
+    dialog --colors --title 'End messages' --msgbox "$(cat $XTEMPMES)" 20 85
+    exit 1
 fi
 
 MYPWD=$(pwd)
 HOMESLACK="$MYPWD"
-
-XTEMPOUT=$(mktemp -p /tmp -t pbupgradeout.XXXXXX)
-XTEMPMES=$(mktemp -p /tmp -t pbupgrademes.XXXXXX)
 
 if [ "$XNEW" = 'yes' ] ;then
     XUPSYSTEM=off
@@ -89,7 +81,8 @@ xmaster () {
     xsel1=$1;shift;xsel2=$1;shift;xsel3=$1;shift;xsel4=$1;shift;xsel5=$1;shift
     xsel6=$1;shift;xsel7=$1;shift;xsel8=$1;shift;xsel9=$1;shift;xsel10=$1;shift
     xsel11=$1;shift;xsel12=$1;shift;xsel13=$1;shift
-    pactit=$(mygt 'Main menu');pactit="pbupgrade: $pactit"
+    pactit=$(mygt 'Main menu')
+    pactit="pbupgrade: $pactit"
     dialog --colors --title "$pactit" --default-item $defitem --defaultno \
 	--separate-output --item-help --help-button --help-status --checklist \
 	'Choose your actions below after you have launch the \Zbpbaspire*\ZB script' 0 100 13 \
@@ -139,14 +132,11 @@ while [ $bclaide -eq 1 ] ;do
 	done
 	ditem=$xitem;bclaide=1;pacaide=
 	if [ "$xitem" = system ] ;then
-	    pacaide='Upgrade your Slackware system with the last current fetched'
-	    pacaide="$pacaide before.\nUses Slackpkg."
+	    pacaide='Upgrade your Slackware system with the last current fetched\nUses Slackpkg.'
 	elif [ "$xitem" = compat32 ] ;then
 	    pacaide='Upgrade the Alien Bob 32 bits compatible mode.'
 	elif [ "$xitem" = mozilla ] ;then
-	    pacaide='Upgrade the Firefox and Thunderbird products.'
-	    pacaide="${pacaide}\nThey should be downloaded and put in the"
-	    pacaise="$pacaide packages/Mozilla directory before."
+	    pacaide='Upgrade the Firefox and Thunderbird products.\nThey should be downloaded and put in the packages/Mozilla directory before.'
 	elif [ "$(echo "$xitem"|cut -c1-8)" = packages ] ;then
 	    xpacaide "$xitem"
 	elif [ "$xitem" = frameworks ] ;then
@@ -156,29 +146,29 @@ while [ $bclaide -eq 1 ] ;do
 	elif [ "$xitem" = tesseract4 ] ;then
 	    xpacaide packages4/tesseract4
 	elif [ "$xitem" = bumblebee ] ;then
-	    pacaide='Upgrade your Bumblebee packages if they are in sync with'
-	    pacaide="$pacaide the upgraded Slackware.\n"
-	    pacaide="${pacaide}Done on another machine for exemple."
+	    pacaide='Upgrade your Bumblebee packages if they are in sync with the upgraded Slackware.\nDone on another machine for exemple.'
 	elif [ "$xitem" = recreate ] ;then
-	    pacaide='Redo the packages which are here in sources form.'
-	    pacaide="$pacaide\nIf not already done on this machine or another."
+	    pacaide='Redo the packages which are here in sources form.\nIf not already done on this machine or another.'
 	elif [ "$xitem" = recreatebumblebee ] ;then
-	    pacaide='Redo the Bumblebee packages.'
-	    pacaide="$pacaide\nIf not already done on this machine or another."
+	    pacaide='Redo the Bumblebee packages.\nIf not already done on this machine or another.\nYou should reboot after upgrading system packages and before doing this action else the Bumblebee packages wont built.'
 	fi
 	dialog --colors --title "$xitem" --msgbox "$pacaide" 20 80
     fi
 done
 
+DACTION=$(mygt 'Actions which were done')
+
 if [ $XTEST -ne 1 ] ;then
     if [ ! $UID = 0 ]; then
-        echo "This script must be done as root. Exit." > $XTEMPMES
-        dialog --colors --title 'Actions which were done' --msgbox "$(cat $XTEMPMES)" 20 80
+        mygt 'This script must be done as root. Exit.' > $XTEMPMES
+        dialog --colors --title "$DACTION" --msgbox "$(cat $XTEMPMES)" 20 80
         rm -f $XTEMPOUT
         rm -f $XTEMPMES
 	exit 1
     fi
 fi
+
+XEND=0
 
 while read i;test "$i" != "" ;do
     if [ "$(echo $i|cut -c1-4)" = 'HELP' ] ;then
@@ -197,85 +187,84 @@ while read i;test "$i" != "" ;do
 
 	    if [ $? -ne 0 ] ;then
 		rm -f $XTEMPOUT
-		rm -f $XTEMPMES
-		echo 'Abort : voir erreurs precedentes.'
-		exit 1
+		which slackpkg 2> $XTEMPMES
+		mygt 'Abort : see previous errors.' >> $XTEMPMES
+		XEND=1
+		break
 	    fi
 	fi
-	echo "Upgrade system fait." >> $XTEMPMES
+	mygt "Upgrade system done." >> $XTEMPMES
     elif [ "$i" = compat32 ] ;then
 	if [ $XTEST -ne 1 ] ;then
 	    upgradepkg --reinstall --install-new current/*.t?z
 	    upgradepkg --install-new current/slackware64-compat32/*/*.t?z
 	fi
-	echo "Upgrade Alien Bob multilib fait." >> $XTEMPMES
+	mygt "Upgrade Alien Bob multilib done." >> $XTEMPMES
     elif [ "$i" = mozilla ] ;then
 	if [ $XTEST -ne 1 ] ;then
 	    $HOMESLACK/pbslacks/pbupgrademoz
 	fi
-	echo "Upgrade Mozilla fait." >> $XTEMPMES
+	mygt "Upgrade Mozilla done." >> $XTEMPMES
     elif [ "$i" = packages ] ;then
 	if [ $XTEST -ne 1 ] ;then
 	    upgradepkg --install-new packages/*.t?z
 	fi
-	echo "Upgrade packages fait." >> $XTEMPMES
+	mygt "Upgrade packages done." >> $XTEMPMES
     elif [ "$i" = packages2 ] ;then
 	if [ $XTEST -ne 1 ] ;then
 	    upgradepkg --install-new packages2/*.t?z
 	fi
-	echo "Upgrade packages2 fait." >> $XTEMPMES
+	mygt "Upgrade packages2 done." >> $XTEMPMES
     elif [ "$i" = packages3 ] ;then
 	if [ $XTEST -ne 1 ] ;then
 	    upgradepkg --install-new packages3/*.t?z
 	fi
-	echo "Upgrade packages3 fait." >> $XTEMPMES
+	mygt "Upgrade packages3 done." >> $XTEMPMES
     elif [ "$i" = packages4 ] ;then
 	if [ $XTEST -ne 1 ] ;then
 	    upgradepkg --install-new packages4/*.t?z
 	fi
-	echo "Upgrade packages4 fait." >> $XTEMPMES
+	mygt "Upgrade packages4 done." >> $XTEMPMES
     elif [ "$i" = frameworks ] ;then
 	if [ $XTEST -ne 1 ] ;then
 	    upgradepkg --install-new packages4/frameworks/*.t?z
 	fi
-	echo "Upgrade frameworks fait." >> $XTEMPMES
+	mygt "Upgrade frameworks done." >> $XTEMPMES
     elif [ "$i" = audacity ] ;then
 	if [ $XTEST -ne 1 ] ;then
 	    upgradepkg --install-new packages4/audacity/*.t?z
 	fi
-	echo "Upgrade audacity fait." >> $XTEMPMES
+	mygt "Upgrade audacity done." >> $XTEMPMES
     elif [ "$i" = tesseract4 ] ;then
 	if [ $XTEST -ne 1 ] ;then
 	    upgradepkg --install-new packages4/tesseract4/*.t?z
 	    cp packages4/tesseract4/xsane2tess* /usr/bin
 	fi
-	echo "Upgrade tesseract4 fait." >> $XTEMPMES
+	mygt "Upgrade tesseract4 done." >> $XTEMPMES
     elif [ "$i" = bumblebee ] ;then
 	if [ $XTEST -ne 1 ] ;then
 	    $HOMESLACK/pbslacks/pbupgradebumblebee
 	fi
-	echo "Upgrade Bumblebee fait." >> $XTEMPMES
+	mygt "Upgrade Bumblebee done." >> $XTEMPMES
     elif [ "$i" = recreate ] ;then
 	if [ $XTEST -ne 1 ] ;then
 	    $HOMESLACK/pbslacks/pbcompilepost
 	fi
-	echo "Recreate source packages fait." >> $XTEMPMES
+	mygt "Recreate source packages done." >> $XTEMPMES
     elif [ "$i" = recreatebumblebee ] ;then
 	if [ $XTEST -ne 1 ] ;then
 	    $HOMESLACK/pbslacks/pbcompilebumblebee
 	fi
-	echo "Recreate source Bumblebee fait." >> $XTEMPMES
+	mygt "Recreate source Bumblebee done." >> $XTEMPMES
     fi
 done < $XTEMPOUT
 
-XEND=0
-
-if [ ! -f "$XTEMPMES" -o $(cat "$XTEMPMES"|wc -c) -eq 0 ] ;then
-    echo "No action was demanded. Exit." > $XTEMPMES
+if [ ! -f "$XTEMPMES" -o ! -s "$XTEMPMES" ] ;then
+    mygt "No action was demanded. Exit." > $XTEMPMES
     XEND=1
 fi
 
-dialog --colors --title 'Actions which were done' --msgbox "$(cat $XTEMPMES)" 20 80
+dialog --colors --title "$DACTION" --msgbox "$(cat $XTEMPMES)" 20 80
 
 if [ $XEND -eq 1 ] ;then
     rm -f $XTEMPOUT
@@ -381,5 +370,4 @@ xend >> $XTEMPMES
 if [ -f "$XTEMPMES" ] ;then
     dialog --colors --title 'End messages' --msgbox "$(cat $XTEMPMES)" 20 80
 fi
-
 rm -f $XTEMPMES
