pbslacks V0.59-20210223 Date : 23 fevrier 2021 Auteur : Pierre Brochard (pierre.brochard.1982@m4x.org) Copyright et droits d'auteurs : Pierre Brochard

diff --git a/builds/sbo/kde4/other/qt/qt.SlackBuild b/builds/sbo/kde4/other/qt/qt.SlackBuild
--- a/builds/sbo/kde4/other/qt/qt.SlackBuild
+++ b/builds/sbo/kde4/other/qt/qt.SlackBuild
@@ -31,10 +31,10 @@ cd $(dirname $0) ; CWD=$(pwd)
 PKGNAM=qt
 
 # Versions, build and tag for combined qt4 and qt4webkit packages.
-QTVERSION=$(ls qt-*.tar.?z* | rev | cut -f 3- -d . | cut -f 1 -d - | rev)
+QTVERSION=$(ls qt/qt-*.tar.?z* | rev | cut -f 3- -d . | cut -f 1 -d - | rev)
 # Adjust the combined package $BUILD in qt-nowebkit.SlackBuild:
-QTBUILD=$(grep BUILD= qt-nowebkit.SlackBuild | cut -f 2 -d - | cut -f 1 -d \})
-QTTAG=$(grep TAG= qt-nowebkit.SlackBuild | cut -f 2 -d - | cut -f 1 -d \})
+QTBUILD=$(grep BUILD= qt/qt.SlackBuild | cut -f 2 -d - | cut -f 1 -d \})
+QTTAG=$(grep TAG= qt/qt.SlackBuild | cut -f 2 -d - | cut -f 1 -d \})
 
 WEBKITNAM=qtwebkit
 WEBKITVERSION=$(ls qtwebkit/qtwebkit-*.tar.?z* | rev | cut -f 3- -d . | cut -f 1 -d - | rev)
@@ -90,7 +90,10 @@ QTWEBKITNAM="$OUTPUT/${WEBKITNAM}-${WEBKITVERSION}-${ARCH}-${WEBKITBUILD}${WEBKI
 
 # Build Qt and package it without WebKit:
 if [ ! -f "$QTNAM" ] ;then
-    sh ./qt-nowebkit.SlackBuild
+    (
+	cd qt
+	sh ./qt.SlackBuild
+    )
     if [ ! -r "$QTNAM" ]; then
 	echo "FATAL:  Failed to build Qt package without WebKit."
 	exit 1
@@ -107,29 +110,31 @@ rm -f "$QTWEBKITNAM"
     sh ./qtwebkit.SlackBuild
 )
 if [ ! -r "$QTWEBKITNAM" ]; then
-  echo "FATAL:  Failed to build QtWebKit standalone package."
-  exit 1
+    echo "FATAL:  Failed to build QtWebKit standalone package."
+    exit 1
 fi
 
 # Combine the packages:
 rm -rf $PKG
 mkdir -p $PKG
-( cd $PKG
-  /sbin/explodepkg "$QTWEBKITNAM"
-  /sbin/explodepkg "$QTNAM"
-  cat $TMP/package-qtwebkit/install/doinst.sh | grep '^(' >> install/doinst.sh
-  mv usr/doc/qtwebkit-* usr/doc/${PKGNAM}-*
-  # Remove rpaths:
-  for file in $(find . | xargs file | grep -e "executable" -e "shared object" | \
-		    grep ELF | cut -f 1 -d : 2> /dev/null) ; do
-    if [ ! "$(patchelf --print-rpath $file 2> /dev/null)" = "" ]; then
-      patchelf --remove-rpath $file
-    fi
-  done
-  # Don't ship .la files:
-  rm -f usr/lib${LIBDIRSUFFIX}/*.la
-  rm -f usr/lib${LIBDIRSUFFIX}/qt/lib/*.la
-  /sbin/makepkg -l y -c n "$QTNAM"
+(
+    cd $PKG
+    /sbin/explodepkg "$QTWEBKITNAM"
+    /sbin/explodepkg "$QTNAM"
+    cat $TMP/package-qtwebkit/install/doinst.sh | grep '^(' >> install/doinst.sh
+    mv usr/doc/qtwebkit-* usr/doc/${PKGNAM}-*
+    # Remove rpaths:
+    for file in $(find . | xargs file | \
+		      grep -e "executable" -e "shared object" | \
+		      grep ELF | cut -f 1 -d : 2> /dev/null) ; do
+	if [ ! "$(patchelf --print-rpath $file 2> /dev/null)" = "" ]; then
+	    patchelf --remove-rpath $file
+	fi
+    done
+    # Don't ship .la files:
+    rm -f usr/lib${LIBDIRSUFFIX}/*.la
+    rm -f usr/lib${LIBDIRSUFFIX}/qt/lib/*.la
+    /sbin/makepkg -l y -c n "$QTNAM"
 )
 
 # Remove intermediate qtwebkit package:
